dataset : "cifar10"
workers : 4
epochs : 300
start_epoch : 0
train_batch : 128
test_batch : 100
lr : 0.1
drop : 0
schedule : [150, 225] #step lr schedule
gamma : 0.1
momentum : 0.9
weight_decay : 0.0005
arch : "resnet"
depth : 20
manualSeed : null



